language: node_js
node_js:
  - 0.10
notifications:
  email:
    on_success: never
env:
  - secure: "EX+2LyiAB2LIrsWUck8ftal/mM88V/abk3NQto1/Gz+j/Ov8YdM3Hc0VgvnEriz1Xo1C56necsCpv9E5l1EJkM+i0WVeIQwK4D7FylvlLMmm8mAJeNvaq/YREtLL/fNLqyZ5AuLDq5rnMeG/e6Dx7emOA9h+nvyVpT3Eojvkcjo="

