language: node_js
node_js:
- "0.10"
notifications:
  email:
    on_success: never
env:
- secure: HhvWoR88+eCkm+YXaIfGuBFMoBKxbnXFN618XqXlBwbpz+1se3YOxv0kX7265dDf7z3xPggkCrmQ+B+AinczUQ3n6rN9Q9utDD6HM5BBdcIeQ/zLQ8n9aQyCaQloThu+eE/ni2GpJ8oO+JlK2ox5Xoen1s4uTD6SxrCPPHAwgec=
deploy:
  provider: npm
  email: carlos.manzanares+npm@gmail.com
  api_key:
    secure: MJW7xF24bUAz/aAVndqeJmD2SLvjp8kpimjS/8z+Zz4IIXyk4MdBzpjeLZfvo0/fsR9JcB4YVvO0yQNvdB3b6PLnfw4oIw3O96TaRLred4rNrdiO2kwkD0y/Wb901s1OMQwOp6FGVs9bSBhooGMrp+eEnYglBKhV+pX5onw6OtA=
  on:
    tags: true
    repo: cmanzana/node-figaro
after_success:
- "echo 'test' >> README.md"
- "git config --global user.email 'carlos.manzanares+github@gmail.com'"
- "git config --global user.name cmanzana"
- "git add README.md"
- "git commit -m 'travis commit [ci skip]'"
- "git push https://a4632b4c24b2785d0d585e315580e2c7f769908d@github.com/cmanzana/node-figaro.git"
