language: node_js
node_js:
  - 0.10
notifications:
  email:
    on_success: never
env:
  - secure: "iRaRuqffUGc1TpFiDJYmmAb1ieFfMvEliLGYBQ8pO75VLMQEnRfmoCIVJSo/qmlsq7jN2/4TErmdO6qLY3FsvPdHXTgfeFcDuqb4FNNhmU+eKAL5spr6WUPIEKiyfj+v6Cf4WfAvUjWmm3Qv5i5qrYt49STQXLnMYK/hHV24mL8="
