language: node_js
node_js:
  - 0.10
notifications:
  email:
    on_success: never
env:
  - secure: "Xye6Z1rUoaglOtlStweM9HAhrPwrgSOU4LU7wd8S1bT6s8yAlblEKnpPYdQd+aWfhdYCtplEBzoYnxclzHrHnU3w8L4gITnTJHnW/ZJEkF7hFGX1AYos1IJlj8evBGrS3RLFS+USOjqv0jw6XjSz1Bz2EBYvSTYQrnCYP/HEEi8="

